[2021-04-24 11:45:30,249] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: project_dag.Stage_songs 2020-09-01T00:00:00+00:00 [queued]>
[2021-04-24 11:45:30,962] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: project_dag.Stage_songs 2020-09-01T00:00:00+00:00 [queued]>
[2021-04-24 11:45:30,963] {taskinstance.py:1068} INFO - 
--------------------------------------------------------------------------------
[2021-04-24 11:45:30,964] {taskinstance.py:1069} INFO - Starting attempt 1 of 2
[2021-04-24 11:45:30,966] {taskinstance.py:1070} INFO - 
--------------------------------------------------------------------------------
[2021-04-24 11:45:31,555] {taskinstance.py:1089} INFO - Executing <Task(StageToRedshiftOperator): Stage_songs> on 2020-09-01T00:00:00+00:00
[2021-04-24 11:45:31,935] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'project_dag', 'Stage_songs', '2020-09-01T00:00:00+00:00', '--job-id', '92', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/udac_example_dag.py', '--cfg-path', '/tmp/tmp0jtntn9g', '--error-file', '/tmp/tmp37pil854']
[2021-04-24 11:45:31,936] {standard_task_runner.py:77} INFO - Job 92: Subtask Stage_songs
[2021-04-24 11:45:31,701] {standard_task_runner.py:52} INFO - Started process 222 to run task
[2021-04-24 11:45:34,412] {logging_mixin.py:104} INFO - Running <TaskInstance: project_dag.Stage_songs 2020-09-01T00:00:00+00:00 [running]> on host 88dcd2a12842
[2021-04-24 11:45:35,625] {taskinstance.py:1283} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=ernest@gmail.com.com
AIRFLOW_CTX_DAG_OWNER=udacity
AIRFLOW_CTX_DAG_ID=project_dag
AIRFLOW_CTX_TASK_ID=Stage_songs
AIRFLOW_CTX_EXECUTION_DATE=2020-09-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2020-09-01T00:00:00+00:00
[2021-04-24 11:45:35,630] {stage_redshift.py:38} INFO - Start implementation of StageToRedshiftOperator
[2021-04-24 11:45:35,925] {taskinstance.py:1482} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1138, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1311, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1341, in _execute_task
    result = task_copy.execute(context=context)
  File "/opt/airflow/plugins/operators/stage_redshift.py", line 39, in execute
    aws_hook = AwsHook(self.aws_credentials_id)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/contrib/hooks/aws_hook.py", line 41, in __init__
    super().__init__(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/amazon/aws/hooks/base_aws.py", line 360, in __init__
    raise AirflowException('Either client_type or resource_type must be provided.')
airflow.exceptions.AirflowException: Either client_type or resource_type must be provided.
[2021-04-24 11:45:35,973] {taskinstance.py:1532} INFO - Marking task as UP_FOR_RETRY. dag_id=project_dag, task_id=Stage_songs, execution_date=20200901T000000, start_date=20210424T114530, end_date=20210424T114535
[2021-04-24 11:45:36,349] {local_task_job.py:146} INFO - Task exited with return code 1
[2021-04-26 09:07:58,485] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: project_dag.Stage_songs 2020-09-01T00:00:00+00:00 [queued]>
[2021-04-26 09:07:59,324] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: project_dag.Stage_songs 2020-09-01T00:00:00+00:00 [queued]>
[2021-04-26 09:07:59,326] {taskinstance.py:1068} INFO - 
--------------------------------------------------------------------------------
[2021-04-26 09:07:59,330] {taskinstance.py:1069} INFO - Starting attempt 1 of 2
[2021-04-26 09:07:59,334] {taskinstance.py:1070} INFO - 
--------------------------------------------------------------------------------
[2021-04-26 09:08:00,307] {taskinstance.py:1089} INFO - Executing <Task(StageToRedshiftOperator): Stage_songs> on 2020-09-01T00:00:00+00:00
[2021-04-26 09:08:01,064] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'project_dag', 'Stage_songs', '2020-09-01T00:00:00+00:00', '--job-id', '20', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/udac_example_dag.py', '--cfg-path', '/tmp/tmpo8acxnhz', '--error-file', '/tmp/tmp6ow33133']
[2021-04-26 09:08:01,065] {standard_task_runner.py:77} INFO - Job 20: Subtask Stage_songs
[2021-04-26 09:08:00,533] {standard_task_runner.py:52} INFO - Started process 87 to run task
[2021-04-26 09:08:05,232] {logging_mixin.py:104} INFO - Running <TaskInstance: project_dag.Stage_songs 2020-09-01T00:00:00+00:00 [running]> on host b5c40a6f08c7
[2021-04-26 09:08:07,997] {taskinstance.py:1283} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=ernestoffor@gmail.com.com
AIRFLOW_CTX_DAG_OWNER=udacity
AIRFLOW_CTX_DAG_ID=project_dag
AIRFLOW_CTX_TASK_ID=Stage_songs
AIRFLOW_CTX_EXECUTION_DATE=2020-09-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2020-09-01T00:00:00+00:00
[2021-04-26 09:08:08,007] {stage_redshift.py:63} INFO - Start implementation of StageToRedshiftOperator
[2021-04-26 09:08:08,008] {stage_redshift.py:68} INFO - Preparing destination Redshift table
[2021-04-26 09:08:08,533] {base.py:78} INFO - Using connection to: id: redshift. Host: redshift.cxvwoeu3kuea.us-west-2.redshift.amazonaws.com, Port: 5439, Schema: dev, Login: awsuser, Password: XXXXXXXX, extra: None
[2021-04-26 09:08:10,305] {dbapi.py:180} INFO - Running statement: DELETE FROM staging_songs, parameters: None
[2021-04-26 09:08:10,755] {dbapi.py:186} INFO - Rows affected: 0
[2021-04-26 09:08:11,125] {stage_redshift.py:71} INFO - Getting data from S3 to Redshift
[2021-04-26 09:08:11,268] {base.py:78} INFO - Using connection to: id: redshift. Host: redshift.cxvwoeu3kuea.us-west-2.redshift.amazonaws.com, Port: 5439, Schema: dev, Login: awsuser, Password: XXXXXXXX, extra: None
[2021-04-26 09:08:12,695] {dbapi.py:180} INFO - Running statement: 
             COPY staging_songs 
             FROM 's3://udacity-dend/song_data/*/*/*/'
             FORMAT AS JSON 'JSON 'auto''
             CREDENTIALS
             'aws_access_key_id=None;aws_secret_access_key=None'
                , parameters: None
[2021-04-26 09:08:13,114] {taskinstance.py:1482} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1138, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1311, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1341, in _execute_task
    result = task_copy.execute(context=context)
  File "/opt/airflow/plugins/operators/stage_redshift.py", line 81, in execute
    redshift.run(execution_sql)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/hooks/dbapi.py", line 184, in run
    cur.execute(sql_statement)
psycopg2.errors.SyntaxError: syntax error at or near "auto"
LINE 4:              FORMAT AS JSON 'JSON 'auto''
                                           ^

[2021-04-26 09:08:13,225] {taskinstance.py:1532} INFO - Marking task as UP_FOR_RETRY. dag_id=project_dag, task_id=Stage_songs, execution_date=20200901T000000, start_date=20210426T090758, end_date=20210426T090813
[2021-04-26 09:08:15,068] {local_task_job.py:146} INFO - Task exited with return code 1
[2021-04-26 12:36:12,203] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: project_dag.Stage_songs 2020-09-01T00:00:00+00:00 [queued]>
[2021-04-26 12:36:13,697] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: project_dag.Stage_songs 2020-09-01T00:00:00+00:00 [queued]>
[2021-04-26 12:36:13,698] {taskinstance.py:1068} INFO - 
--------------------------------------------------------------------------------
[2021-04-26 12:36:13,698] {taskinstance.py:1069} INFO - Starting attempt 1 of 2
[2021-04-26 12:36:13,698] {taskinstance.py:1070} INFO - 
--------------------------------------------------------------------------------
[2021-04-26 12:36:14,006] {taskinstance.py:1089} INFO - Executing <Task(StageToRedshiftOperator): Stage_songs> on 2020-09-01T00:00:00+00:00
[2021-04-26 12:36:14,092] {standard_task_runner.py:52} INFO - Started process 115 to run task
[2021-04-26 12:36:14,163] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'project_dag', 'Stage_songs', '2020-09-01T00:00:00+00:00', '--job-id', '31', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/udac_example_dag.py', '--cfg-path', '/tmp/tmp7wqiqnfg', '--error-file', '/tmp/tmpzo9_6xd_']
[2021-04-26 12:36:14,182] {standard_task_runner.py:77} INFO - Job 31: Subtask Stage_songs
[2021-04-26 12:36:18,312] {logging_mixin.py:104} INFO - Running <TaskInstance: project_dag.Stage_songs 2020-09-01T00:00:00+00:00 [running]> on host 0f1e1da1f4f6
[2021-04-26 12:36:18,995] {taskinstance.py:1283} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=ernestoffor@gmail.com.com
AIRFLOW_CTX_DAG_OWNER=udacity
AIRFLOW_CTX_DAG_ID=project_dag
AIRFLOW_CTX_TASK_ID=Stage_songs
AIRFLOW_CTX_EXECUTION_DATE=2020-09-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2020-09-01T00:00:00+00:00
[2021-04-26 12:36:19,003] {stage_redshift.py:62} INFO - Start implementation of StageToRedshiftOperator
[2021-04-26 12:36:19,011] {stage_redshift.py:67} INFO - Preparing destination Redshift table
[2021-04-26 12:36:19,039] {base.py:78} INFO - Using connection to: id: redshift. Host: redshift.cxvwoeu3kuea.us-west-2.redshift.amazonaws.com, Port: 5439, Schema: dev, Login: awsuser, Password: XXXXXXXX, extra: None
[2021-04-26 12:36:20,532] {dbapi.py:180} INFO - Running statement: DELETE FROM staging_songs, parameters: None
[2021-04-26 12:36:20,973] {dbapi.py:186} INFO - Rows affected: 0
[2021-04-26 12:36:21,327] {stage_redshift.py:70} INFO - Getting data from S3 to Redshift
[2021-04-26 12:36:21,414] {base.py:78} INFO - Using connection to: id: redshift. Host: redshift.cxvwoeu3kuea.us-west-2.redshift.amazonaws.com, Port: 5439, Schema: dev, Login: awsuser, Password: XXXXXXXX, extra: None
[2021-04-26 12:36:22,851] {dbapi.py:180} INFO - Running statement: 
             COPY staging_songs 
             FROM '/offor_data/song_data/*/*/*/'
             FORMAT AS JSON 'JSON 'auto''
                  , parameters: None
[2021-04-26 12:36:23,269] {taskinstance.py:1482} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1138, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1311, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1341, in _execute_task
    result = task_copy.execute(context=context)
  File "/opt/airflow/plugins/operators/stage_redshift.py", line 80, in execute
    redshift.run(execution_sql)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/hooks/dbapi.py", line 184, in run
    cur.execute(sql_statement)
psycopg2.errors.SyntaxError: syntax error at or near "auto"
LINE 4:              FORMAT AS JSON 'JSON 'auto''
                                           ^

[2021-04-26 12:36:23,299] {taskinstance.py:1532} INFO - Marking task as UP_FOR_RETRY. dag_id=project_dag, task_id=Stage_songs, execution_date=20200901T000000, start_date=20210426T123612, end_date=20210426T123623
[2021-04-26 12:36:24,014] {local_task_job.py:146} INFO - Task exited with return code 1
[2021-04-27 20:39:54,257] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: project_dag.Stage_songs 2020-09-01T00:00:00+00:00 [queued]>
[2021-04-27 20:39:54,947] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: project_dag.Stage_songs 2020-09-01T00:00:00+00:00 [queued]>
[2021-04-27 20:39:54,962] {taskinstance.py:1068} INFO - 
--------------------------------------------------------------------------------
[2021-04-27 20:39:54,971] {taskinstance.py:1069} INFO - Starting attempt 1 of 2
[2021-04-27 20:39:54,971] {taskinstance.py:1070} INFO - 
--------------------------------------------------------------------------------
[2021-04-27 20:39:55,591] {taskinstance.py:1089} INFO - Executing <Task(StageToRedshiftOperator): Stage_songs> on 2020-09-01T00:00:00+00:00
[2021-04-27 20:39:56,524] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'project_dag', 'Stage_songs', '2020-09-01T00:00:00+00:00', '--job-id', '93', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/udac_example_dag.py', '--cfg-path', '/tmp/tmpmv1yczjj', '--error-file', '/tmp/tmptamspm16']
[2021-04-27 20:39:56,525] {standard_task_runner.py:77} INFO - Job 93: Subtask Stage_songs
[2021-04-27 20:39:56,328] {standard_task_runner.py:52} INFO - Started process 224 to run task
[2021-04-27 20:39:59,154] {logging_mixin.py:104} INFO - Running <TaskInstance: project_dag.Stage_songs 2020-09-01T00:00:00+00:00 [running]> on host 478c7ec349b0
[2021-04-27 20:40:01,030] {taskinstance.py:1283} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=ernestoffor@gmail.com.com
AIRFLOW_CTX_DAG_OWNER=udacity
AIRFLOW_CTX_DAG_ID=project_dag
AIRFLOW_CTX_TASK_ID=Stage_songs
AIRFLOW_CTX_EXECUTION_DATE=2020-09-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2020-09-01T00:00:00+00:00
[2021-04-27 20:40:01,030] {stage_redshift.py:67} INFO - Start implementation of StageToRedshiftOperator
[2021-04-27 20:40:01,031] {stage_redshift.py:74} INFO - Preparing destination Redshift table
[2021-04-27 20:40:01,159] {base.py:78} INFO - Using connection to: id: redshift. Host: redshift.cxvwoeu3kuea.us-west-2.redshift.amazonaws.com, Port: 5439, Schema: dev, Login: awsuser, Password: XXXXXXXX, extra: None
[2021-04-27 20:40:02,625] {dbapi.py:180} INFO - Running statement: DELETE FROM staging_songs, parameters: None
[2021-04-27 20:40:03,068] {dbapi.py:186} INFO - Rows affected: 0
[2021-04-27 20:40:03,411] {stage_redshift.py:77} INFO - Getting data from S3 to Redshift
[2021-04-27 20:40:07,237] {taskinstance.py:1482} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1138, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1311, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1341, in _execute_task
    result = task_copy.execute(context=context)
  File "/opt/airflow/plugins/operators/stage_redshift.py", line 83, in execute
    s3.get_credentials().access_key,
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/amazon/aws/hooks/base_aws.py", line 478, in get_credentials
    return session.get_credentials().get_frozen_credentials()
AttributeError: 'NoneType' object has no attribute 'get_frozen_credentials'
[2021-04-27 20:40:07,250] {taskinstance.py:1532} INFO - Marking task as UP_FOR_RETRY. dag_id=project_dag, task_id=Stage_songs, execution_date=20200901T000000, start_date=20210427T203954, end_date=20210427T204007
[2021-04-27 20:40:07,786] {local_task_job.py:146} INFO - Task exited with return code 1
