[2021-04-24 11:46:05,053] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: project_dag.Stage_songs 2020-11-01T00:00:00+00:00 [queued]>
[2021-04-24 11:46:05,147] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: project_dag.Stage_songs 2020-11-01T00:00:00+00:00 [queued]>
[2021-04-24 11:46:05,147] {taskinstance.py:1068} INFO - 
--------------------------------------------------------------------------------
[2021-04-24 11:46:05,147] {taskinstance.py:1069} INFO - Starting attempt 1 of 2
[2021-04-24 11:46:05,147] {taskinstance.py:1070} INFO - 
--------------------------------------------------------------------------------
[2021-04-24 11:46:05,244] {taskinstance.py:1089} INFO - Executing <Task(StageToRedshiftOperator): Stage_songs> on 2020-11-01T00:00:00+00:00
[2021-04-24 11:46:05,259] {standard_task_runner.py:52} INFO - Started process 247 to run task
[2021-04-24 11:46:05,348] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'project_dag', 'Stage_songs', '2020-11-01T00:00:00+00:00', '--job-id', '103', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/udac_example_dag.py', '--cfg-path', '/tmp/tmp132u5ljo', '--error-file', '/tmp/tmpeukpncj7']
[2021-04-24 11:46:05,355] {standard_task_runner.py:77} INFO - Job 103: Subtask Stage_songs
[2021-04-24 11:46:06,057] {logging_mixin.py:104} INFO - Running <TaskInstance: project_dag.Stage_songs 2020-11-01T00:00:00+00:00 [running]> on host 88dcd2a12842
[2021-04-24 11:46:06,857] {taskinstance.py:1283} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=ernest@gmail.com.com
AIRFLOW_CTX_DAG_OWNER=udacity
AIRFLOW_CTX_DAG_ID=project_dag
AIRFLOW_CTX_TASK_ID=Stage_songs
AIRFLOW_CTX_EXECUTION_DATE=2020-11-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2020-11-01T00:00:00+00:00
[2021-04-24 11:46:06,870] {stage_redshift.py:38} INFO - Start implementation of StageToRedshiftOperator
[2021-04-24 11:46:06,983] {taskinstance.py:1482} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1138, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1311, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1341, in _execute_task
    result = task_copy.execute(context=context)
  File "/opt/airflow/plugins/operators/stage_redshift.py", line 39, in execute
    aws_hook = AwsHook(self.aws_credentials_id)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/contrib/hooks/aws_hook.py", line 41, in __init__
    super().__init__(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/amazon/aws/hooks/base_aws.py", line 360, in __init__
    raise AirflowException('Either client_type or resource_type must be provided.')
airflow.exceptions.AirflowException: Either client_type or resource_type must be provided.
[2021-04-24 11:46:07,015] {taskinstance.py:1532} INFO - Marking task as UP_FOR_RETRY. dag_id=project_dag, task_id=Stage_songs, execution_date=20201101T000000, start_date=20210424T114605, end_date=20210424T114607
[2021-04-24 11:46:07,296] {local_task_job.py:146} INFO - Task exited with return code 1
[2021-04-26 09:08:27,562] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: project_dag.Stage_songs 2020-11-01T00:00:00+00:00 [queued]>
[2021-04-26 09:08:29,319] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: project_dag.Stage_songs 2020-11-01T00:00:00+00:00 [queued]>
[2021-04-26 09:08:29,416] {taskinstance.py:1068} INFO - 
--------------------------------------------------------------------------------
[2021-04-26 09:08:29,416] {taskinstance.py:1069} INFO - Starting attempt 1 of 2
[2021-04-26 09:08:29,416] {taskinstance.py:1070} INFO - 
--------------------------------------------------------------------------------
[2021-04-26 09:08:30,651] {taskinstance.py:1089} INFO - Executing <Task(StageToRedshiftOperator): Stage_songs> on 2020-11-01T00:00:00+00:00
[2021-04-26 09:08:31,865] {standard_task_runner.py:52} INFO - Started process 111 to run task
[2021-04-26 09:08:32,562] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'project_dag', 'Stage_songs', '2020-11-01T00:00:00+00:00', '--job-id', '30', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/udac_example_dag.py', '--cfg-path', '/tmp/tmpi7wkn4nm', '--error-file', '/tmp/tmp3wmjt5n3']
[2021-04-26 09:08:32,728] {standard_task_runner.py:77} INFO - Job 30: Subtask Stage_songs
[2021-04-26 09:08:35,467] {logging_mixin.py:104} INFO - Running <TaskInstance: project_dag.Stage_songs 2020-11-01T00:00:00+00:00 [running]> on host b5c40a6f08c7
[2021-04-26 09:08:37,301] {taskinstance.py:1283} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=ernestoffor@gmail.com.com
AIRFLOW_CTX_DAG_OWNER=udacity
AIRFLOW_CTX_DAG_ID=project_dag
AIRFLOW_CTX_TASK_ID=Stage_songs
AIRFLOW_CTX_EXECUTION_DATE=2020-11-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2020-11-01T00:00:00+00:00
[2021-04-26 09:08:37,380] {stage_redshift.py:63} INFO - Start implementation of StageToRedshiftOperator
[2021-04-26 09:08:37,381] {stage_redshift.py:68} INFO - Preparing destination Redshift table
[2021-04-26 09:08:37,771] {base.py:78} INFO - Using connection to: id: redshift. Host: redshift.cxvwoeu3kuea.us-west-2.redshift.amazonaws.com, Port: 5439, Schema: dev, Login: awsuser, Password: XXXXXXXX, extra: None
[2021-04-26 09:08:39,351] {dbapi.py:180} INFO - Running statement: DELETE FROM staging_songs, parameters: None
[2021-04-26 09:08:39,970] {dbapi.py:186} INFO - Rows affected: 0
[2021-04-26 09:08:40,283] {stage_redshift.py:71} INFO - Getting data from S3 to Redshift
[2021-04-26 09:08:40,708] {base.py:78} INFO - Using connection to: id: redshift. Host: redshift.cxvwoeu3kuea.us-west-2.redshift.amazonaws.com, Port: 5439, Schema: dev, Login: awsuser, Password: XXXXXXXX, extra: None
[2021-04-26 09:08:42,238] {dbapi.py:180} INFO - Running statement: 
             COPY staging_songs 
             FROM 's3://udacity-dend/song_data/*/*/*/'
             FORMAT AS JSON 'JSON 'auto''
             CREDENTIALS
             'aws_access_key_id=None;aws_secret_access_key=None'
                , parameters: None
[2021-04-26 09:08:42,689] {taskinstance.py:1482} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1138, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1311, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1341, in _execute_task
    result = task_copy.execute(context=context)
  File "/opt/airflow/plugins/operators/stage_redshift.py", line 81, in execute
    redshift.run(execution_sql)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/hooks/dbapi.py", line 184, in run
    cur.execute(sql_statement)
psycopg2.errors.SyntaxError: syntax error at or near "auto"
LINE 4:              FORMAT AS JSON 'JSON 'auto''
                                           ^

[2021-04-26 09:08:42,725] {taskinstance.py:1532} INFO - Marking task as UP_FOR_RETRY. dag_id=project_dag, task_id=Stage_songs, execution_date=20201101T000000, start_date=20210426T090827, end_date=20210426T090842
[2021-04-26 09:08:45,277] {local_task_job.py:188} WARNING - State of this instance has been externally set to up_for_retry. Terminating instance.
[2021-04-26 09:08:45,464] {process_utils.py:100} INFO - Sending Signals.SIGTERM to GPID 111
[2021-04-26 09:08:45,553] {process_utils.py:66} INFO - Process psutil.Process(pid=111, status='terminated', exitcode=1, started='09:08:30') (111) terminated with exit code 1
[2021-04-26 12:36:04,568] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: project_dag.Stage_songs 2020-11-01T00:00:00+00:00 [queued]>
[2021-04-26 12:36:05,345] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: project_dag.Stage_songs 2020-11-01T00:00:00+00:00 [queued]>
[2021-04-26 12:36:05,345] {taskinstance.py:1068} INFO - 
--------------------------------------------------------------------------------
[2021-04-26 12:36:05,345] {taskinstance.py:1069} INFO - Starting attempt 1 of 2
[2021-04-26 12:36:05,346] {taskinstance.py:1070} INFO - 
--------------------------------------------------------------------------------
[2021-04-26 12:36:05,771] {taskinstance.py:1089} INFO - Executing <Task(StageToRedshiftOperator): Stage_songs> on 2020-11-01T00:00:00+00:00
[2021-04-26 12:36:06,901] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'project_dag', 'Stage_songs', '2020-11-01T00:00:00+00:00', '--job-id', '23', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/udac_example_dag.py', '--cfg-path', '/tmp/tmpe9i5c2ed', '--error-file', '/tmp/tmp8ptz7_5b']
[2021-04-26 12:36:06,915] {standard_task_runner.py:77} INFO - Job 23: Subtask Stage_songs
[2021-04-26 12:36:06,510] {standard_task_runner.py:52} INFO - Started process 107 to run task
[2021-04-26 12:36:11,409] {logging_mixin.py:104} INFO - Running <TaskInstance: project_dag.Stage_songs 2020-11-01T00:00:00+00:00 [running]> on host 0f1e1da1f4f6
[2021-04-26 12:36:13,595] {taskinstance.py:1283} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=ernestoffor@gmail.com.com
AIRFLOW_CTX_DAG_OWNER=udacity
AIRFLOW_CTX_DAG_ID=project_dag
AIRFLOW_CTX_TASK_ID=Stage_songs
AIRFLOW_CTX_EXECUTION_DATE=2020-11-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2020-11-01T00:00:00+00:00
[2021-04-26 12:36:13,602] {stage_redshift.py:62} INFO - Start implementation of StageToRedshiftOperator
[2021-04-26 12:36:13,604] {stage_redshift.py:67} INFO - Preparing destination Redshift table
[2021-04-26 12:36:13,810] {base.py:78} INFO - Using connection to: id: redshift. Host: redshift.cxvwoeu3kuea.us-west-2.redshift.amazonaws.com, Port: 5439, Schema: dev, Login: awsuser, Password: XXXXXXXX, extra: None
[2021-04-26 12:36:15,916] {dbapi.py:180} INFO - Running statement: DELETE FROM staging_songs, parameters: None
[2021-04-26 12:36:16,623] {dbapi.py:186} INFO - Rows affected: 0
[2021-04-26 12:36:16,909] {stage_redshift.py:70} INFO - Getting data from S3 to Redshift
[2021-04-26 12:36:16,951] {base.py:78} INFO - Using connection to: id: redshift. Host: redshift.cxvwoeu3kuea.us-west-2.redshift.amazonaws.com, Port: 5439, Schema: dev, Login: awsuser, Password: XXXXXXXX, extra: None
[2021-04-26 12:36:18,350] {dbapi.py:180} INFO - Running statement: 
             COPY staging_songs 
             FROM '/offor_data/song_data/*/*/*/'
             FORMAT AS JSON 'JSON 'auto''
                  , parameters: None
[2021-04-26 12:36:18,752] {taskinstance.py:1482} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1138, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1311, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1341, in _execute_task
    result = task_copy.execute(context=context)
  File "/opt/airflow/plugins/operators/stage_redshift.py", line 80, in execute
    redshift.run(execution_sql)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/hooks/dbapi.py", line 184, in run
    cur.execute(sql_statement)
psycopg2.errors.SyntaxError: syntax error at or near "auto"
LINE 4:              FORMAT AS JSON 'JSON 'auto''
                                           ^

[2021-04-26 12:36:19,676] {taskinstance.py:1532} INFO - Marking task as UP_FOR_RETRY. dag_id=project_dag, task_id=Stage_songs, execution_date=20201101T000000, start_date=20210426T123604, end_date=20210426T123619
[2021-04-26 12:36:20,337] {local_task_job.py:146} INFO - Task exited with return code 1
[2021-04-27 20:40:08,881] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: project_dag.Stage_songs 2020-11-01T00:00:00+00:00 [queued]>
[2021-04-27 20:40:09,005] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: project_dag.Stage_songs 2020-11-01T00:00:00+00:00 [queued]>
[2021-04-27 20:40:09,006] {taskinstance.py:1068} INFO - 
--------------------------------------------------------------------------------
[2021-04-27 20:40:09,006] {taskinstance.py:1069} INFO - Starting attempt 1 of 2
[2021-04-27 20:40:09,006] {taskinstance.py:1070} INFO - 
--------------------------------------------------------------------------------
[2021-04-27 20:40:09,117] {taskinstance.py:1089} INFO - Executing <Task(StageToRedshiftOperator): Stage_songs> on 2020-11-01T00:00:00+00:00
[2021-04-27 20:40:09,444] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'project_dag', 'Stage_songs', '2020-11-01T00:00:00+00:00', '--job-id', '98', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/udac_example_dag.py', '--cfg-path', '/tmp/tmpzlh99esz', '--error-file', '/tmp/tmpf0r4vlb5']
[2021-04-27 20:40:09,445] {standard_task_runner.py:77} INFO - Job 98: Subtask Stage_songs
[2021-04-27 20:40:09,265] {standard_task_runner.py:52} INFO - Started process 234 to run task
[2021-04-27 20:40:09,891] {logging_mixin.py:104} INFO - Running <TaskInstance: project_dag.Stage_songs 2020-11-01T00:00:00+00:00 [running]> on host 478c7ec349b0
[2021-04-27 20:40:10,886] {taskinstance.py:1283} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=ernestoffor@gmail.com.com
AIRFLOW_CTX_DAG_OWNER=udacity
AIRFLOW_CTX_DAG_ID=project_dag
AIRFLOW_CTX_TASK_ID=Stage_songs
AIRFLOW_CTX_EXECUTION_DATE=2020-11-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2020-11-01T00:00:00+00:00
[2021-04-27 20:40:10,887] {stage_redshift.py:67} INFO - Start implementation of StageToRedshiftOperator
[2021-04-27 20:40:10,893] {stage_redshift.py:74} INFO - Preparing destination Redshift table
[2021-04-27 20:40:11,170] {base.py:78} INFO - Using connection to: id: redshift. Host: redshift.cxvwoeu3kuea.us-west-2.redshift.amazonaws.com, Port: 5439, Schema: dev, Login: awsuser, Password: XXXXXXXX, extra: None
[2021-04-27 20:40:12,673] {dbapi.py:180} INFO - Running statement: DELETE FROM staging_songs, parameters: None
[2021-04-27 20:40:13,132] {dbapi.py:186} INFO - Rows affected: 0
[2021-04-27 20:40:13,429] {stage_redshift.py:77} INFO - Getting data from S3 to Redshift
[2021-04-27 20:40:15,724] {taskinstance.py:1482} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1138, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1311, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1341, in _execute_task
    result = task_copy.execute(context=context)
  File "/opt/airflow/plugins/operators/stage_redshift.py", line 83, in execute
    s3.get_credentials().access_key,
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/amazon/aws/hooks/base_aws.py", line 478, in get_credentials
    return session.get_credentials().get_frozen_credentials()
AttributeError: 'NoneType' object has no attribute 'get_frozen_credentials'
[2021-04-27 20:40:15,728] {taskinstance.py:1532} INFO - Marking task as UP_FOR_RETRY. dag_id=project_dag, task_id=Stage_songs, execution_date=20201101T000000, start_date=20210427T204008, end_date=20210427T204015
[2021-04-27 20:40:15,955] {local_task_job.py:146} INFO - Task exited with return code 1
