[2021-04-24 11:46:03,556] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: project_dag.Stage_songs 2020-10-01T00:00:00+00:00 [queued]>
[2021-04-24 11:46:03,737] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: project_dag.Stage_songs 2020-10-01T00:00:00+00:00 [queued]>
[2021-04-24 11:46:03,738] {taskinstance.py:1068} INFO - 
--------------------------------------------------------------------------------
[2021-04-24 11:46:03,738] {taskinstance.py:1069} INFO - Starting attempt 1 of 2
[2021-04-24 11:46:03,768] {taskinstance.py:1070} INFO - 
--------------------------------------------------------------------------------
[2021-04-24 11:46:03,970] {taskinstance.py:1089} INFO - Executing <Task(StageToRedshiftOperator): Stage_songs> on 2020-10-01T00:00:00+00:00
[2021-04-24 11:46:03,990] {standard_task_runner.py:52} INFO - Started process 244 to run task
[2021-04-24 11:46:04,095] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'project_dag', 'Stage_songs', '2020-10-01T00:00:00+00:00', '--job-id', '100', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/udac_example_dag.py', '--cfg-path', '/tmp/tmpc1hbwx4q', '--error-file', '/tmp/tmpsfz75mj1']
[2021-04-24 11:46:04,138] {standard_task_runner.py:77} INFO - Job 100: Subtask Stage_songs
[2021-04-24 11:46:05,020] {logging_mixin.py:104} INFO - Running <TaskInstance: project_dag.Stage_songs 2020-10-01T00:00:00+00:00 [running]> on host 88dcd2a12842
[2021-04-24 11:46:05,485] {taskinstance.py:1283} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=ernest@gmail.com.com
AIRFLOW_CTX_DAG_OWNER=udacity
AIRFLOW_CTX_DAG_ID=project_dag
AIRFLOW_CTX_TASK_ID=Stage_songs
AIRFLOW_CTX_EXECUTION_DATE=2020-10-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2020-10-01T00:00:00+00:00
[2021-04-24 11:46:05,489] {stage_redshift.py:38} INFO - Start implementation of StageToRedshiftOperator
[2021-04-24 11:46:05,565] {taskinstance.py:1482} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1138, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1311, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1341, in _execute_task
    result = task_copy.execute(context=context)
  File "/opt/airflow/plugins/operators/stage_redshift.py", line 39, in execute
    aws_hook = AwsHook(self.aws_credentials_id)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/contrib/hooks/aws_hook.py", line 41, in __init__
    super().__init__(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/amazon/aws/hooks/base_aws.py", line 360, in __init__
    raise AirflowException('Either client_type or resource_type must be provided.')
airflow.exceptions.AirflowException: Either client_type or resource_type must be provided.
[2021-04-24 11:46:05,620] {taskinstance.py:1532} INFO - Marking task as UP_FOR_RETRY. dag_id=project_dag, task_id=Stage_songs, execution_date=20201001T000000, start_date=20210424T114603, end_date=20210424T114605
[2021-04-24 11:46:05,860] {local_task_job.py:146} INFO - Task exited with return code 1
[2021-04-26 09:08:17,732] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: project_dag.Stage_songs 2020-10-01T00:00:00+00:00 [queued]>
[2021-04-26 09:08:18,151] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: project_dag.Stage_songs 2020-10-01T00:00:00+00:00 [queued]>
[2021-04-26 09:08:18,152] {taskinstance.py:1068} INFO - 
--------------------------------------------------------------------------------
[2021-04-26 09:08:18,152] {taskinstance.py:1069} INFO - Starting attempt 1 of 2
[2021-04-26 09:08:18,152] {taskinstance.py:1070} INFO - 
--------------------------------------------------------------------------------
[2021-04-26 09:08:18,582] {taskinstance.py:1089} INFO - Executing <Task(StageToRedshiftOperator): Stage_songs> on 2020-10-01T00:00:00+00:00
[2021-04-26 09:08:19,044] {standard_task_runner.py:52} INFO - Started process 104 to run task
[2021-04-26 09:08:19,351] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'project_dag', 'Stage_songs', '2020-10-01T00:00:00+00:00', '--job-id', '27', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/udac_example_dag.py', '--cfg-path', '/tmp/tmp1680jvzg', '--error-file', '/tmp/tmp1_05mbw9']
[2021-04-26 09:08:19,352] {standard_task_runner.py:77} INFO - Job 27: Subtask Stage_songs
[2021-04-26 09:08:21,087] {logging_mixin.py:104} INFO - Running <TaskInstance: project_dag.Stage_songs 2020-10-01T00:00:00+00:00 [running]> on host b5c40a6f08c7
[2021-04-26 09:08:21,728] {taskinstance.py:1283} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=ernestoffor@gmail.com.com
AIRFLOW_CTX_DAG_OWNER=udacity
AIRFLOW_CTX_DAG_ID=project_dag
AIRFLOW_CTX_TASK_ID=Stage_songs
AIRFLOW_CTX_EXECUTION_DATE=2020-10-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2020-10-01T00:00:00+00:00
[2021-04-26 09:08:21,729] {stage_redshift.py:63} INFO - Start implementation of StageToRedshiftOperator
[2021-04-26 09:08:21,730] {stage_redshift.py:68} INFO - Preparing destination Redshift table
[2021-04-26 09:08:22,588] {base.py:78} INFO - Using connection to: id: redshift. Host: redshift.cxvwoeu3kuea.us-west-2.redshift.amazonaws.com, Port: 5439, Schema: dev, Login: awsuser, Password: XXXXXXXX, extra: None
[2021-04-26 09:08:24,306] {dbapi.py:180} INFO - Running statement: DELETE FROM staging_songs, parameters: None
[2021-04-26 09:08:24,767] {dbapi.py:186} INFO - Rows affected: 0
[2021-04-26 09:08:25,118] {stage_redshift.py:71} INFO - Getting data from S3 to Redshift
[2021-04-26 09:08:25,236] {base.py:78} INFO - Using connection to: id: redshift. Host: redshift.cxvwoeu3kuea.us-west-2.redshift.amazonaws.com, Port: 5439, Schema: dev, Login: awsuser, Password: XXXXXXXX, extra: None
[2021-04-26 09:08:26,696] {dbapi.py:180} INFO - Running statement: 
             COPY staging_songs 
             FROM 's3://udacity-dend/song_data/*/*/*/'
             FORMAT AS JSON 'JSON 'auto''
             CREDENTIALS
             'aws_access_key_id=None;aws_secret_access_key=None'
                , parameters: None
[2021-04-26 09:08:27,135] {taskinstance.py:1482} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1138, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1311, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1341, in _execute_task
    result = task_copy.execute(context=context)
  File "/opt/airflow/plugins/operators/stage_redshift.py", line 81, in execute
    redshift.run(execution_sql)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/hooks/dbapi.py", line 184, in run
    cur.execute(sql_statement)
psycopg2.errors.SyntaxError: syntax error at or near "auto"
LINE 4:              FORMAT AS JSON 'JSON 'auto''
                                           ^

[2021-04-26 09:08:27,204] {taskinstance.py:1532} INFO - Marking task as UP_FOR_RETRY. dag_id=project_dag, task_id=Stage_songs, execution_date=20201001T000000, start_date=20210426T090817, end_date=20210426T090827
[2021-04-26 09:08:29,527] {local_task_job.py:146} INFO - Task exited with return code 1
[2021-04-26 12:36:05,521] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: project_dag.Stage_songs 2020-10-01T00:00:00+00:00 [queued]>
[2021-04-26 12:36:07,024] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: project_dag.Stage_songs 2020-10-01T00:00:00+00:00 [queued]>
[2021-04-26 12:36:07,024] {taskinstance.py:1068} INFO - 
--------------------------------------------------------------------------------
[2021-04-26 12:36:07,025] {taskinstance.py:1069} INFO - Starting attempt 1 of 2
[2021-04-26 12:36:07,025] {taskinstance.py:1070} INFO - 
--------------------------------------------------------------------------------
[2021-04-26 12:36:07,806] {taskinstance.py:1089} INFO - Executing <Task(StageToRedshiftOperator): Stage_songs> on 2020-10-01T00:00:00+00:00
[2021-04-26 12:36:08,682] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'project_dag', 'Stage_songs', '2020-10-01T00:00:00+00:00', '--job-id', '26', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/udac_example_dag.py', '--cfg-path', '/tmp/tmpkljrc_oj', '--error-file', '/tmp/tmpfi03waqr']
[2021-04-26 12:36:08,874] {standard_task_runner.py:77} INFO - Job 26: Subtask Stage_songs
[2021-04-26 12:36:08,365] {standard_task_runner.py:52} INFO - Started process 110 to run task
[2021-04-26 12:36:11,422] {logging_mixin.py:104} INFO - Running <TaskInstance: project_dag.Stage_songs 2020-10-01T00:00:00+00:00 [running]> on host 0f1e1da1f4f6
[2021-04-26 12:36:13,624] {taskinstance.py:1283} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=ernestoffor@gmail.com.com
AIRFLOW_CTX_DAG_OWNER=udacity
AIRFLOW_CTX_DAG_ID=project_dag
AIRFLOW_CTX_TASK_ID=Stage_songs
AIRFLOW_CTX_EXECUTION_DATE=2020-10-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2020-10-01T00:00:00+00:00
[2021-04-26 12:36:13,633] {stage_redshift.py:62} INFO - Start implementation of StageToRedshiftOperator
[2021-04-26 12:36:13,633] {stage_redshift.py:67} INFO - Preparing destination Redshift table
[2021-04-26 12:36:13,799] {base.py:78} INFO - Using connection to: id: redshift. Host: redshift.cxvwoeu3kuea.us-west-2.redshift.amazonaws.com, Port: 5439, Schema: dev, Login: awsuser, Password: XXXXXXXX, extra: None
[2021-04-26 12:36:15,864] {dbapi.py:180} INFO - Running statement: DELETE FROM staging_songs, parameters: None
[2021-04-26 12:36:16,295] {dbapi.py:186} INFO - Rows affected: 0
[2021-04-26 12:36:16,583] {stage_redshift.py:70} INFO - Getting data from S3 to Redshift
[2021-04-26 12:36:16,715] {base.py:78} INFO - Using connection to: id: redshift. Host: redshift.cxvwoeu3kuea.us-west-2.redshift.amazonaws.com, Port: 5439, Schema: dev, Login: awsuser, Password: XXXXXXXX, extra: None
[2021-04-26 12:36:18,123] {dbapi.py:180} INFO - Running statement: 
             COPY staging_songs 
             FROM '/offor_data/song_data/*/*/*/'
             FORMAT AS JSON 'JSON 'auto''
                  , parameters: None
[2021-04-26 12:36:18,505] {taskinstance.py:1482} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1138, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1311, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1341, in _execute_task
    result = task_copy.execute(context=context)
  File "/opt/airflow/plugins/operators/stage_redshift.py", line 80, in execute
    redshift.run(execution_sql)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/hooks/dbapi.py", line 184, in run
    cur.execute(sql_statement)
psycopg2.errors.SyntaxError: syntax error at or near "auto"
LINE 4:              FORMAT AS JSON 'JSON 'auto''
                                           ^

[2021-04-26 12:36:19,669] {taskinstance.py:1532} INFO - Marking task as UP_FOR_RETRY. dag_id=project_dag, task_id=Stage_songs, execution_date=20201001T000000, start_date=20210426T123605, end_date=20210426T123619
[2021-04-26 12:36:20,318] {local_task_job.py:146} INFO - Task exited with return code 1
[2021-04-27 20:39:58,477] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: project_dag.Stage_songs 2020-10-01T00:00:00+00:00 [queued]>
[2021-04-27 20:39:58,976] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: project_dag.Stage_songs 2020-10-01T00:00:00+00:00 [queued]>
[2021-04-27 20:39:58,981] {taskinstance.py:1068} INFO - 
--------------------------------------------------------------------------------
[2021-04-27 20:39:58,982] {taskinstance.py:1069} INFO - Starting attempt 1 of 2
[2021-04-27 20:39:58,982] {taskinstance.py:1070} INFO - 
--------------------------------------------------------------------------------
[2021-04-27 20:39:59,646] {taskinstance.py:1089} INFO - Executing <Task(StageToRedshiftOperator): Stage_songs> on 2020-10-01T00:00:00+00:00
[2021-04-27 20:40:00,390] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'project_dag', 'Stage_songs', '2020-10-01T00:00:00+00:00', '--job-id', '96', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/udac_example_dag.py', '--cfg-path', '/tmp/tmp2qxtchz9', '--error-file', '/tmp/tmpxixqzzml']
[2021-04-27 20:40:00,391] {standard_task_runner.py:77} INFO - Job 96: Subtask Stage_songs
[2021-04-27 20:40:00,152] {standard_task_runner.py:52} INFO - Started process 229 to run task
[2021-04-27 20:40:01,262] {logging_mixin.py:104} INFO - Running <TaskInstance: project_dag.Stage_songs 2020-10-01T00:00:00+00:00 [running]> on host 478c7ec349b0
[2021-04-27 20:40:02,038] {taskinstance.py:1283} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=ernestoffor@gmail.com.com
AIRFLOW_CTX_DAG_OWNER=udacity
AIRFLOW_CTX_DAG_ID=project_dag
AIRFLOW_CTX_TASK_ID=Stage_songs
AIRFLOW_CTX_EXECUTION_DATE=2020-10-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2020-10-01T00:00:00+00:00
[2021-04-27 20:40:02,063] {stage_redshift.py:67} INFO - Start implementation of StageToRedshiftOperator
[2021-04-27 20:40:02,068] {stage_redshift.py:74} INFO - Preparing destination Redshift table
[2021-04-27 20:40:02,211] {base.py:78} INFO - Using connection to: id: redshift. Host: redshift.cxvwoeu3kuea.us-west-2.redshift.amazonaws.com, Port: 5439, Schema: dev, Login: awsuser, Password: XXXXXXXX, extra: None
[2021-04-27 20:40:03,725] {dbapi.py:180} INFO - Running statement: DELETE FROM staging_songs, parameters: None
[2021-04-27 20:40:04,205] {dbapi.py:186} INFO - Rows affected: 0
[2021-04-27 20:40:04,552] {stage_redshift.py:77} INFO - Getting data from S3 to Redshift
[2021-04-27 20:40:07,244] {taskinstance.py:1482} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1138, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1311, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1341, in _execute_task
    result = task_copy.execute(context=context)
  File "/opt/airflow/plugins/operators/stage_redshift.py", line 83, in execute
    s3.get_credentials().access_key,
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/amazon/aws/hooks/base_aws.py", line 478, in get_credentials
    return session.get_credentials().get_frozen_credentials()
AttributeError: 'NoneType' object has no attribute 'get_frozen_credentials'
[2021-04-27 20:40:07,264] {taskinstance.py:1532} INFO - Marking task as UP_FOR_RETRY. dag_id=project_dag, task_id=Stage_songs, execution_date=20201001T000000, start_date=20210427T203958, end_date=20210427T204007
[2021-04-27 20:40:07,987] {local_task_job.py:146} INFO - Task exited with return code 1
